// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package scrumptious.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Scrumptious module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Recipe_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Scrumptious.ACT_Recipe_Create");
		return builder;
	}

	public static void aCT_Recipe_Create(IContext context)
	{
		aCT_Recipe_CreateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Recipe_EditBuilder(
		scrumptious.proxies.Recipe _recipe
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Scrumptious.ACT_Recipe_Edit");
		builder = builder.withParam("Recipe", _recipe);
		return builder;
	}

	public static void aCT_Recipe_Edit(
		IContext context,
		scrumptious.proxies.Recipe _recipe
	)
	{
		aCT_Recipe_EditBuilder(
				_recipe
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Recipe_SaveBuilder(
		scrumptious.proxies.Recipe _recipe
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Scrumptious.ACT_Recipe_Save");
		builder = builder.withParam("Recipe", _recipe);
		return builder;
	}

	public static void aCT_Recipe_Save(
		IContext context,
		scrumptious.proxies.Recipe _recipe
	)
	{
		aCT_Recipe_SaveBuilder(
				_recipe
			)
			.execute(context);
	}
}
