// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package scrumptious.proxies;

public class Recipe implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject recipeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Scrumptious.Recipe";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Description("Description"),
		Ingredients("Ingredients"),
		Instructions("Instructions"),
		CookingTime("CookingTime"),
		Rating("Rating"),
		Photo("Photo"),
		Recipe_Photo("Scrumptious.Recipe_Photo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Recipe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Recipe(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject recipeMendixObject)
	{
		if (recipeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, recipeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.recipeMendixObject = recipeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static scrumptious.proxies.Recipe initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new scrumptious.proxies.Recipe(context, mendixObject);
	}

	public static scrumptious.proxies.Recipe load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return scrumptious.proxies.Recipe.initialize(context, mendixObject);
	}

	public static java.util.List<scrumptious.proxies.Recipe> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> scrumptious.proxies.Recipe.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Ingredients
	 */
	public final java.lang.String getIngredients()
	{
		return getIngredients(getContext());
	}

	/**
	 * @param context
	 * @return value of Ingredients
	 */
	public final java.lang.String getIngredients(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Ingredients.toString());
	}

	/**
	 * Set value of Ingredients
	 * @param ingredients
	 */
	public final void setIngredients(java.lang.String ingredients)
	{
		setIngredients(getContext(), ingredients);
	}

	/**
	 * Set value of Ingredients
	 * @param context
	 * @param ingredients
	 */
	public final void setIngredients(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ingredients)
	{
		getMendixObject().setValue(context, MemberNames.Ingredients.toString(), ingredients);
	}

	/**
	 * @return value of Instructions
	 */
	public final java.lang.String getInstructions()
	{
		return getInstructions(getContext());
	}

	/**
	 * @param context
	 * @return value of Instructions
	 */
	public final java.lang.String getInstructions(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Instructions.toString());
	}

	/**
	 * Set value of Instructions
	 * @param instructions
	 */
	public final void setInstructions(java.lang.String instructions)
	{
		setInstructions(getContext(), instructions);
	}

	/**
	 * Set value of Instructions
	 * @param context
	 * @param instructions
	 */
	public final void setInstructions(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instructions)
	{
		getMendixObject().setValue(context, MemberNames.Instructions.toString(), instructions);
	}

	/**
	 * @return value of CookingTime
	 */
	public final java.lang.Integer getCookingTime()
	{
		return getCookingTime(getContext());
	}

	/**
	 * @param context
	 * @return value of CookingTime
	 */
	public final java.lang.Integer getCookingTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CookingTime.toString());
	}

	/**
	 * Set value of CookingTime
	 * @param cookingtime
	 */
	public final void setCookingTime(java.lang.Integer cookingtime)
	{
		setCookingTime(getContext(), cookingtime);
	}

	/**
	 * Set value of CookingTime
	 * @param context
	 * @param cookingtime
	 */
	public final void setCookingTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cookingtime)
	{
		getMendixObject().setValue(context, MemberNames.CookingTime.toString(), cookingtime);
	}

	/**
	 * @return value of Rating
	 */
	public final java.lang.Integer getRating()
	{
		return getRating(getContext());
	}

	/**
	 * @param context
	 * @return value of Rating
	 */
	public final java.lang.Integer getRating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Rating.toString());
	}

	/**
	 * Set value of Rating
	 * @param rating
	 */
	public final void setRating(java.lang.Integer rating)
	{
		setRating(getContext(), rating);
	}

	/**
	 * Set value of Rating
	 * @param context
	 * @param rating
	 */
	public final void setRating(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rating)
	{
		getMendixObject().setValue(context, MemberNames.Rating.toString(), rating);
	}

	/**
	  * The contents of the binary field will be written to the output stream.
	  * The output stream will be closed at the end.
	  *
	  * @param context
	  * @param outputStream
	  */
	public final void getPhoto(com.mendix.systemwideinterfaces.core.IContext context, java.io.OutputStream outputStream)
	{
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.Photo.toString());
		binary.retrieveValue(context, outputStream);
	}

	/**
	  * Stores the bytes from the given InputStream.
	  *
	  * Please note that the input stream will be immediately sent to the data store,
	  * whether you commit the Mendix object or not.
	  *
	  * @param context
	  * @param inputStream
	  * @param length the number of bytes in the stream
	  */
	public final void setPhoto(com.mendix.systemwideinterfaces.core.IContext context, java.io.InputStream inputStream, long length)
	{
		if (getMendixObject().getState() == com.mendix.systemwideinterfaces.core.IMendixObject.ObjectState.INSTANTIATED) {
			try { commit(); } catch (com.mendix.core.CoreException ex) { }
		}
		com.mendix.core.objectmanagement.member.MendixBinary binary = (com.mendix.core.objectmanagement.member.MendixBinary) getMendixObject().getMember(context, MemberNames.Photo.toString());
		binary.storeValue(context, inputStream, length);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Recipe_Photo
	 */
	public final scrumptious.proxies.Photo getRecipe_Photo() throws com.mendix.core.CoreException
	{
		return getRecipe_Photo(getContext());
	}

	/**
	 * @param context
	 * @return value of Recipe_Photo
	 * @throws com.mendix.core.CoreException
	 */
	public final scrumptious.proxies.Photo getRecipe_Photo(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		scrumptious.proxies.Photo result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Recipe_Photo.toString());
		if (identifier != null) {
			result = scrumptious.proxies.Photo.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Recipe_Photo
	 * @param recipe_photo
	 */
	public final void setRecipe_Photo(scrumptious.proxies.Photo recipe_photo)
	{
		setRecipe_Photo(getContext(), recipe_photo);
	}

	/**
	 * Set value of Recipe_Photo
	 * @param context
	 * @param recipe_photo
	 */
	public final void setRecipe_Photo(com.mendix.systemwideinterfaces.core.IContext context, scrumptious.proxies.Photo recipe_photo)
	{
		if (recipe_photo == null) {
			getMendixObject().setValue(context, MemberNames.Recipe_Photo.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Recipe_Photo.toString(), recipe_photo.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return recipeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final scrumptious.proxies.Recipe that = (scrumptious.proxies.Recipe) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
